name: example
description: Dart and Flutter sealed or union class generator and annotations, with match methods and other utilities.
repository: https://github.com/omegasoft7/dart_sealed/tree/master/example
homepage: https://github.com/omegasoft7/dart_sealed

version: 1.13.2

# example package should not be published
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # use fixed version dependency
  sealed_class_annotations: '1.13.2'

dev_dependencies:
  # use fixed version dependency
  sealed_class_creators: '1.13.2'
  lints: any
  test: any
  build_runner: any

# # remove this on pub branch
# dependency_overrides:
#   sealed_class_annotations:
#     path: ../sealed_class_annotations
#   sealed_class_writer:
#     path: ../sealed_class_writer
#   sealed_class_creators:
#     path: ../sealed_class_creators
