targets:
  $default:
    builders:
      sealed_class_creators:
        enabled: true

builders:
  sealed_class_creators:
    target: ":sealed_class_creators"
    import: "package:sealed_class_creators/sealed_class_creators.dart"
    builder_factories: [ "sealedGeneratorsBuilder" ]
    build_extensions: { ".dart": [ ".sealed.dart" ] }
    auto_apply: dependents
    build_to: source
