#!/bin/bash

echo HEADER analyze

pushd sealed_class_annotations || exit 1
echo NOTE sealed_class_annotations
dart analyze || exit 1
popd || exit 1

pushd sealed_class_writer || exit 1
echo NOTE sealed_class_writer
dart analyze || exit 1
popd || exit 1

pushd sealed_class_creators || exit 1
echo NOTE sealed_class_creators
dart analyze || exit 1
popd || exit 1

pushd example || exit 1
echo NOTE example
dart analyze || exit 1
popd || exit 1
