#!/bin/bash

echo COPY README FILE

cp README.md sealed_class_annotations/
cp README.md sealed_class_annotations/example/
cp README.md example/
cp README.md sealed_class_creators/
cp README.md sealed_class_creators/example/
cp README.md sealed_class_writer/
cp README.md sealed_class_writer/example/

echo DONE
