#!/bin/bash

echo HEADER format

pushd sealed_class_annotations || exit 1
echo NOTE sealed_class_annotations
dart format --fix lib test
popd || exit 1

pushd sealed_class_writer || exit 1
echo NOTE sealed_class_writer
dart format --fix lib test
popd || exit 1

pushd sealed_class_creators || exit 1
echo NOTE sealed_class_creators
dart format --fix lib test
popd || exit 1

pushd example || exit 1
echo NOTE example
dart format --fix test
popd || exit 1
