#!/bin/bash

echo HEADER init

pushd sealed_class_annotations || exit 1
echo NOTE sealed_class_annotations
dart pub outdated || exit 1
popd || exit 1

pushd sealed_class_writer || exit 1
echo NOTE sealed_class_writer
dart pub outdated || exit 1
popd || exit 1

pushd sealed_class_creators || exit 1
echo NOTE sealed_class_creators
dart pub outdated || exit 1
popd || exit 1

pushd example || exit 1
echo NOTE example
dart pub outdated || exit 1
popd || exit 1
