#!/bin/bash

echo HEADER publish

pushd sealed_class_annotations || exit 1
echo NOTE sealed_class_annotations
dart pub publish || exit 1
popd || exit 1

pushd sealed_class_writer || exit 1
echo NOTE sealed_class_writer
dart pub publish || exit 1
popd || exit 1

pushd sealed_class_creators || exit 1
echo NOTE sealed_class_creators
dart pub publish || exit 1
popd || exit 1
