#!/bin/bash

echo HEADER test

pushd sealed_class_annotations || exit 1
echo NOTE sealed_class_annotations
dart test || exit 1
popd || exit 1

pushd sealed_class_writer || exit 1
echo NOTE sealed_class_writer
dart test || exit 1
popd || exit 1

pushd sealed_class_creators || exit 1
echo NOTE sealed_class_creators
dart test || exit 1
popd || exit 1

pushd example || exit 1
echo NOTE example
dart test || exit 1
popd || exit 1
