name: sealed_class_annotations
description: Dart and Flutter sealed or union class generator and annotations, with match methods and other utilities.
repository: https://github.com/omegasoft7/dart_sealed/tree/master/sealed_class_annotations
homepage: https://github.com/omegasoft7/dart_sealed

version: 1.13.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.8.0
  equatable: ^2.0.0

dev_dependencies:
  lints: any
  test: any

# # remove this on pub branch
# publish_to: 'none'
